### ISSUE TITLE
[Feature Request] Limit characters of a line of lore

### ISSUE THREAD

**Issue by Folas1337** [emanondev/ItemEdit#15]
Hey there,

I'd love to have the config option like lore-line-limit, only that it restricts the amount of characters you can have in one line of lore.

```yaml
  lore-character-limit: 40
```

Cause very long lines in lore are rather annoying and really hard to read, so this would be an awesome addition I think :)

**Comment by emanondev** [comment]
solved, you can see 
```
[...]
blocked:
  [...]
  # How many chars can an item name contains?
  # format codes are NOT ignored
  # this limit is ignored if user has permission itemedit.bypass.rename_length_limit
  # set -1 for no limit
  rename-length-limit: 120
  # How many chars can an item lore line contains?
  # format codes are NOT ignored
  # this limit is ignored if user has permission itemedit.bypass.lore_length_limit
  # set -1 for no limit
  lore-length-limit: 120
```
on config file
